# Site settings
name: Airton Vancin Junior
description: 'A Brazilian web developer, graduate in information systems'
url: http://airtonvancin.com/
baseurl: /
exclude: ['assets','node_modules','components','Gruntfile.js', 'Gulpfile.js', 'package.json', 'bower.json']


# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

source:      .
destination: ./_site
plugins:     ./_plugins
paginate_path: 'blog/page:num'

permalink:   blog/:title/
paginate: 5
