# Site settings
name: Airton Vancin Junior
description: A brazilian web developer
url: http://airton.github.io/
baseurl: /
exclude: ['node_modules', 'Gruntfile.js', 'package.json']


# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

source:      .
destination: ./_site
plugins:     ./_plugins
paginate_path: 'blog/page:num'

permalink:   /:title/
paginate: 5
